Base implementation of controller functions
lukerops/ufes-posts-microservice pull request #22
Opened 2023-05-24 01:06 UTC by brenoSN

2023-05-24 14:34 UTC, joaoferrete commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/service/PostService.kt
> +    }
I liked it.

2023-05-24 14:34 UTC, joaoferrete commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/service/PostService.kt
> +}
I think we can test this function to make sure it's working fine

2023-05-24 14:40 UTC, LazaroJPR commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/controller/PostController.kt
> +    @DeleteMapping("{id}")
Why {id} and no /{id}?

2023-05-24 23:46 UTC, brenoSN commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/controller/PostController.kt
> +    @DeleteMapping("{id}")
{} indicate a path variable, and based on my testing, there is no need to explicitly include a forward slash (/) before it.

2023-05-25 01:10 UTC, joaoferrete commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/controller/PostController.kt
> +    @DeleteMapping("{id}")
Wow, I didn't know that. Interesting...

2023-05-29 14:19 UTC, AddisonAV approved these changes

2023-05-30 19:53 UTC, joaoferrete requested changes

2023-05-30 19:53 UTC, joaoferrete commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/service/PostService.kt
> +}
Remember to add a new line here

2023-06-05 19:45 UTC, joaoferrete approved these changes

2023-06-05 19:45 UTC, merged