Add author service, controller and controller tests
lukerops/ufes-posts-microservice pull request #33
Opened 2023-06-13 00:13 UTC by brenoSN

2023-06-14 23:38 UTC, LazaroJPR commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/controller/AuthorController.kt
> +        }
I think u can do this too:
return author?.let { ResponseEntity.ok(it) } ?: ResponseEntity.notFound().build()

Try it!

2023-06-14 23:38 UTC, LazaroJPR approved these changes

2023-06-19 15:20 UTC, RamonTon approved these changes

2023-06-19 15:29 UTC, joaoferrete requested changes

2023-06-19 15:29 UTC, joaoferrete commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/service/AuthorService.kt
> +            val safeAuthor = author.copy(id = author.id, postId = author.postId, authorId = author.authorId)
If you're using `copy` method, you only need to put the changed paramether

2023-06-19 17:35 UTC, brenoSN commented on post-microsservice/src/main/kotlin/com/example/postmicrosservice/service/AuthorService.kt
> +            val safeAuthor = author.copy(id = author.id, postId = author.postId, authorId = author.authorId)
Removed unnecessary author.id copy

2023-06-19 17:36 UTC, merged